In [18]:
from pyscf import fci, mcscf, scf, gto
from ci_to_2rdm import read_ci_file, update_ci_coeffs
import numpy as np
from scat_lib import run_scattering_csf
from mrh.my_pyscf.fci.csfstring import CSFTransformer

In [3]:
mol = gto.M(atom = 'Be 0 0 0', spin = 0, charge = 0, cart = True, symmetry=False, basis = '3-21g')
mf = scf.HF(mol)
mf.kernel()
casscf = mcscf.CASSCF(mf, 9, 4)
casscf.kernel()

converged SCF energy = -14.4868202421757
CASSCF energy = -14.5314443791087
CASCI E = -14.5314443791087  E(CI) = -14.5314443791087  S^2 = 0.0000000


(np.float64(-14.53144437910874),
 np.float64(-14.53144437910874),
 FCIvector([[-9.50546941e-01,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00,  1.60648050e-01, -1.16415676e-03, ...,
              0.00000000e+00, -5.52216744e-04,  0.00000000e+00],
            [ 0.00000000e+00, -1.16415676e-03, -5.93840779e-05, ...,
              0.00000000e+00,  8.23699212e-05,  0.00000000e+00],
            ...,
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
             -1.14196586e-04,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00, -5.52216744e-04,  8.23699212e-05, ...,
              0.00000000e+00, -1.14196586e-04,  0.00000000e+00],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00, -1.14196570e-04]]),
 array([[ 0.99280987, -0.21571232,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0

In [4]:
occslst = fci.cistring.gen_occslst(range(9), 4 // 2)

In [7]:
casscf.ci

FCIvector([[-9.50546941e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648050e-01, -1.16415676e-03, ...,
             0.00000000e+00, -5.52216744e-04,  0.00000000e+00],
           [ 0.00000000e+00, -1.16415676e-03, -5.93840779e-05, ...,
             0.00000000e+00,  8.23699212e-05,  0.00000000e+00],
           ...,
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
            -1.14196586e-04,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00, -5.52216744e-04,  8.23699212e-05, ...,
             0.00000000e+00, -1.14196586e-04,  0.00000000e+00],
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00, -1.14196570e-04]])

In [40]:
alpha_, beta_, ci = read_ci_file('./321gci_CASCI.txt')

In [15]:
update_ci_coeffs(alpha, beta, ci, casscf, update=True)

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264804e-04, -1.89937272e-04, -3.63020756e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292270e-05,  2.83317760e-05,  5.41490580e-05],
           ...,
           [ 0.00000000e+00, -3.70264804e-04,  5.52292270e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937272e-04,  2.83317760e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020756e-04,  5.41490580e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])

In [16]:
casscf.ci

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264804e-04, -1.89937272e-04, -3.63020756e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292270e-05,  2.83317760e-05,  5.41490580e-05],
           ...,
           [ 0.00000000e+00, -3.70264804e-04,  5.52292270e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937272e-04,  2.83317760e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020756e-04,  5.41490580e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])

In [19]:
transformer = CSFTransformer(9, 2, 2, 1)

In [20]:
csf = transformer.vec_det2csf(casscf.ci)

In [24]:
back_ci = transformer.vec_csf2det(csf)

In [29]:
occslst = fci.cistring.gen_occslst(range(casscf.ncas), (2 + 2) // 2)
alpha = []
beta = []

for i, occs_alpha in enumerate(occslst.tolist()):
    for j, occs_beta in enumerate(occslst.tolist()):
        alpha.append(occs_alpha)
        beta.append(occs_beta)

In [34]:
alpha = np.array(alpha)

In [39]:
alpha

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [7, 8],
       [7, 8],
       [7, 8]])

In [35]:
alpha_

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [7, 8],
       [7, 8],
       [7, 8]])

In [ ]:
update_ci_coeffs(alpha, beta)

np.True_

In [43]:
update_ci_coeffs(alpha_, beta_, back_ci.flatten(), casscf, update = True)

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264949e-04, -1.89937387e-04, -3.63020869e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292827e-05,  2.83318007e-05,  5.41491010e-05],
           ...,
           [ 0.00000000e+00, -3.70264949e-04,  5.52292827e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937387e-04,  2.83318007e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020869e-04,  5.41491010e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])