In [1]:
from pyscf import fci, mcscf, scf, gto
from ci_to_2rdm import read_ci_file, update_ci_coeffs
import numpy as np
from scat_lib import run_scattering_csf
from mrh.my_pyscf.fci.csfstring import CSFTransformer

In [2]:
mol = gto.M(atom = 'Be 0 0 0', spin = 0, charge = 0, cart = True, symmetry=False, basis = '3-21g')
mf = scf.HF(mol)
mf.kernel()
casscf = mcscf.CASSCF(mf, 9, 4)
casscf.kernel()

converged SCF energy = -14.4868202421757
CASSCF energy = -14.5314443791087
CASCI E = -14.5314443791087  E(CI) = -14.5314443791087  S^2 = 0.0000000


(np.float64(-14.53144437910874),
 np.float64(-14.53144437910874),
 FCIvector([[-9.50546941e-01,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00,  1.60648050e-01, -1.16415676e-03, ...,
              0.00000000e+00, -5.52216744e-04,  0.00000000e+00],
            [ 0.00000000e+00, -1.16415676e-03, -5.93840779e-05, ...,
              0.00000000e+00,  8.23699212e-05,  0.00000000e+00],
            ...,
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
             -1.14196586e-04,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00, -5.52216744e-04,  8.23699212e-05, ...,
              0.00000000e+00, -1.14196586e-04,  0.00000000e+00],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00, -1.14196570e-04]]),
 array([[ 0.99280987, -0.21571232,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0

In [3]:
occslst = fci.cistring.gen_occslst(range(9), 4 // 2)

In [4]:
casscf.ci

FCIvector([[-9.50546941e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648050e-01, -1.16415676e-03, ...,
             0.00000000e+00, -5.52216744e-04,  0.00000000e+00],
           [ 0.00000000e+00, -1.16415676e-03, -5.93840779e-05, ...,
             0.00000000e+00,  8.23699212e-05,  0.00000000e+00],
           ...,
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
            -1.14196586e-04,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00, -5.52216744e-04,  8.23699212e-05, ...,
             0.00000000e+00, -1.14196586e-04,  0.00000000e+00],
           [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00, -1.14196570e-04]])

In [5]:
alpha_, beta_, ci = read_ci_file('./321gci_CASCI.txt')

FileNotFoundError: [Errno 2] No such file or directory: './321gci_CASCI.txt'

In [15]:
update_ci_coeffs(alpha, beta, ci, casscf, update=True)

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264804e-04, -1.89937272e-04, -3.63020756e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292270e-05,  2.83317760e-05,  5.41490580e-05],
           ...,
           [ 0.00000000e+00, -3.70264804e-04,  5.52292270e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937272e-04,  2.83317760e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020756e-04,  5.41490580e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])

In [16]:
casscf.ci

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264804e-04, -1.89937272e-04, -3.63020756e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292270e-05,  2.83317760e-05,  5.41490580e-05],
           ...,
           [ 0.00000000e+00, -3.70264804e-04,  5.52292270e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937272e-04,  2.83317760e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020756e-04,  5.41490580e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])

In [6]:
transformer = CSFTransformer(9, 2, 2, 1)

In [7]:
csf = transformer.vec_det2csf(casscf.ci)

In [8]:
back_ci = transformer.vec_csf2det(csf)

In [9]:
occslst = fci.cistring.gen_occslst(range(casscf.ncas), (2 + 2) // 2)
alpha = []
beta = []

for i, occs_alpha in enumerate(occslst.tolist()):
    for j, occs_beta in enumerate(occslst.tolist()):
        alpha.append(occs_alpha)
        beta.append(occs_beta)

In [10]:
alpha = np.array(alpha)

In [11]:
alpha

array([[0, 1],
       [0, 1],
       [0, 1],
       ...,
       [7, 8],
       [7, 8],
       [7, 8]])

In [ ]:
update_ci_coeffs(alpha, beta)

np.True_

In [43]:
update_ci_coeffs(alpha_, beta_, back_ci.flatten(), casscf, update = True)

FCIvector([[ 9.50546942e-01,  0.00000000e+00,  0.00000000e+00, ...,
             0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
           [ 0.00000000e+00,  1.60648310e-01, -1.16414587e-03, ...,
            -3.70264949e-04, -1.89937387e-04, -3.63020869e-04],
           [ 0.00000000e+00, -1.16414587e-03, -5.93942780e-05, ...,
             5.52292827e-05,  2.83318007e-05,  5.41491010e-05],
           ...,
           [ 0.00000000e+00, -3.70264949e-04,  5.52292827e-05, ...,
            -1.14194699e-04, -1.66000000e-10, -5.30000000e-11],
           [ 0.00000000e+00, -1.89937387e-04,  2.83318007e-05, ...,
            -1.66000000e-10, -1.14193734e-04,  1.00000000e-12],
           [ 0.00000000e+00, -3.63020869e-04,  5.41491010e-05, ...,
            -5.30000000e-11,  1.00000000e-12, -1.14194041e-04]])

In [13]:
csf = transformer.vec_det2csf(casscf.ci)

In [51]:
vals, inde, inve= np.unique(csf.round(decimals=10), return_inverse=True, return_index = True)

In [52]:
inve

array([[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 34,  2, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 34,  2,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 13, 23, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 34,  2,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 24, 23, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 24, 23,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 31, 19, 14, 21, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 31, 19, 14, 21, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 

In [32]:
inve.shape

(1, 540)

In [34]:
vals.shape

(41,)

In [65]:
count_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

In [66]:
inde

array([504, 260,  13, 476, 288, 301, 330, 516, 534, 517, 348, 411, 404,
        60, 168, 537, 509, 524, 506, 167,   0, 169, 414,  61, 108, 489,
       433, 461, 329, 316, 413, 166, 533, 308,  12, 515, 392, 514, 273,
       532, 505])

In [38]:
count_index, counts = np.unique_counts(inve)

In [57]:
reduced_dict = {a : np.sqrt(b) for a, b in zip(count_index, counts)}

In [67]:
reduced_dict

{np.int64(0): np.float64(1.0),
 np.int64(1): np.float64(1.7320508075688772),
 np.int64(2): np.float64(1.7320508075688772),
 np.int64(3): np.float64(1.0),
 np.int64(4): np.float64(1.7320508075688772),
 np.int64(5): np.float64(1.0),
 np.int64(6): np.float64(1.7320508075688772),
 np.int64(7): np.float64(2.449489742783178),
 np.int64(8): np.float64(1.7320508075688772),
 np.int64(9): np.float64(1.7320508075688772),
 np.int64(10): np.float64(1.7320508075688772),
 np.int64(11): np.float64(1.4142135623730951),
 np.int64(12): np.float64(1.0),
 np.int64(13): np.float64(1.0),
 np.int64(14): np.float64(1.7320508075688772),
 np.int64(15): np.float64(1.7320508075688772),
 np.int64(16): np.float64(1.7320508075688772),
 np.int64(17): np.float64(1.7320508075688772),
 np.int64(18): np.float64(1.7320508075688772),
 np.int64(19): np.float64(1.7320508075688772),
 np.int64(20): np.float64(20.92844953645635),
 np.int64(21): np.float64(1.7320508075688772),
 np.int64(22): np.float64(1.7320508075688772),
 np.in

In [68]:
reduced_dict = {a : np.sqrt(b) for a, b in enumerate(counts)}

In [69]:
reduced_dict

{0: np.float64(1.0),
 1: np.float64(1.7320508075688772),
 2: np.float64(1.7320508075688772),
 3: np.float64(1.0),
 4: np.float64(1.7320508075688772),
 5: np.float64(1.0),
 6: np.float64(1.7320508075688772),
 7: np.float64(2.449489742783178),
 8: np.float64(1.7320508075688772),
 9: np.float64(1.7320508075688772),
 10: np.float64(1.7320508075688772),
 11: np.float64(1.4142135623730951),
 12: np.float64(1.0),
 13: np.float64(1.0),
 14: np.float64(1.7320508075688772),
 15: np.float64(1.7320508075688772),
 16: np.float64(1.7320508075688772),
 17: np.float64(1.7320508075688772),
 18: np.float64(1.7320508075688772),
 19: np.float64(1.7320508075688772),
 20: np.float64(20.92844953645635),
 21: np.float64(1.7320508075688772),
 22: np.float64(1.7320508075688772),
 23: np.float64(1.7320508075688772),
 24: np.float64(1.4142135623730951),
 25: np.float64(1.7320508075688772),
 26: np.float64(1.0),
 27: np.float64(1.4142135623730951),
 28: np.float64(1.7320508075688772),
 29: np.float64(1.73205080756

In [58]:
np.sum(vals**2)

np.float64(0.936544550925209)

In [62]:
rescaled_csf = np.array([val * reduced_dict[i] for i, val in enumerate(vals)])

In [64]:
np.sum(rescaled_csf**2)

np.float64(0.9999999999179592)

In [60]:
vals

array([-9.50546941e-01, -7.41758717e-02, -3.43953360e-03, -1.39810580e-03,
       -1.05262730e-03, -4.88351800e-04, -4.23024800e-04, -3.65830700e-04,
       -2.85171500e-04, -2.77895500e-04, -2.11847800e-04, -1.93662700e-04,
       -1.93662600e-04, -1.54326000e-04, -1.42669200e-04, -1.14196600e-04,
       -9.79955000e-05, -8.54425000e-05, -5.93841000e-05, -1.61619000e-05,
        0.00000000e+00,  1.93183000e-05,  8.41918000e-05,  8.79351000e-05,
        1.54326000e-04,  1.87052800e-04,  1.93662600e-04,  1.93662700e-04,
        2.00372400e-04,  2.11847800e-04,  4.71036300e-04,  9.56466900e-04,
        1.40678690e-03,  1.64636630e-03,  1.78453660e-03,  2.22804510e-03,
        4.10267270e-03,  1.93687039e-02,  1.98264000e-02,  2.96670315e-02,
        1.60648050e-01])

In [61]:
reduced_dict

{np.int64(0): np.float64(1.0),
 np.int64(1): np.float64(1.7320508075688772),
 np.int64(2): np.float64(1.7320508075688772),
 np.int64(3): np.float64(1.0),
 np.int64(4): np.float64(1.7320508075688772),
 np.int64(5): np.float64(1.0),
 np.int64(6): np.float64(1.7320508075688772),
 np.int64(7): np.float64(2.449489742783178),
 np.int64(8): np.float64(1.7320508075688772),
 np.int64(9): np.float64(1.7320508075688772),
 np.int64(10): np.float64(1.7320508075688772),
 np.int64(11): np.float64(1.4142135623730951),
 np.int64(12): np.float64(1.0),
 np.int64(13): np.float64(1.0),
 np.int64(14): np.float64(1.7320508075688772),
 np.int64(15): np.float64(1.7320508075688772),
 np.int64(16): np.float64(1.7320508075688772),
 np.int64(17): np.float64(1.7320508075688772),
 np.int64(18): np.float64(1.7320508075688772),
 np.int64(19): np.float64(1.7320508075688772),
 np.int64(20): np.float64(20.92844953645635),
 np.int64(21): np.float64(1.7320508075688772),
 np.int64(22): np.float64(1.7320508075688772),
 np.in